### ISSUE TITLE
Stacking screen crashing

### ISSUE THREAD

**Issue by fluidvoice** [pradel/blockstack-wallet#58]
Intermittently it's crashing whenever I open the stacking page.  First it was crashing last night. Then a couple hours later it was OK. This morning crashing again - tried a dozen times.  Will see if I reboot the phone if it still keeps happening. Will append the Android debug info here.

**Comment by fluidvoice** [comment]
Crash
com.facebook.react.common.JavascriptException: TypeError: undefined is not an object (evaluating '(0,b.deserializeCV)(g.Buffer.from(O.stackingInfo.result.slice(2),'hex')).value.data')

This error is located at:
    in Unknown
    in Unknown
    in Unknown
    in Unknown
    in Unknown
    in RCTView
    in View
    in k
    in ForwardRef
    in RCTView
    in View
    in k
    in ForwardRef
    in RCTView
    in View
    in RCTView
    in View
    in p
    in _
    in withTheme(p)
    in B
    in Unknown
    in Unknown
    in R
    in Unknown
    in Unknown
    in Unknown
    in Unknown
    in RCTView
    in View
    in RCTView
    in View
    in RCTView
    in View
    in ForwardRef
    in RCTView
    in View
    in k
    in ForwardRef
    in PanGestureHandler
    in Unknown
    in RCTView
    in View
    in k
    in ForwardRef
    in RCTView
    in View
    in G
    in Unknown
    in RCTView
    in View
    in Unknown
    in RCTView
    in View
    in Unknown
    in w
    in h
    in RNCSafeAreaProvider
    in Unknown
    in Unknown
    in GestureHandlerRootView
    in Unknown
    in G
    in Unknown
    in Unknown
    in Unknown
    in Unknown
    in Unknown
    in Unknown
    in ForwardRef
    in Unknown
    in ForwardRef
    in c
    in RCTView
    in View
    in Portal.Host
    in P
    in Unknown
    in Unknown
    in RCTView
    in View
    in RCTView
    in View
    in C, stack:
<unknown>@2279:1586
mi@99:60183
Dl@99:78547
unstable_runWithPriority@207:3882
<unknown>@99:78167
G@207:2821
n@207:194
y@137:580
callTimers@137:2629
value@44:3350
<unknown>@44:747
value@44:2610
value@44:719
value@-1

 at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:83)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
 at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
 at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
 at android.os.Handler.handleCallback(Handler.java:873)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
 at android.os.Looper.loop(Looper.java:201)
 at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
 at java.lang.Thread.run(Thread.java:764)

**Comment by pradel** [comment]
@fluidvoice thanks for the detailed issue, should be fixed in [v0.3.1](https://github.com/pradel/blockstack-wallet/releases/tag/v0.3.1).
